spring.application.name=libraryApi
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
max.book.value=10